### ISSUE TITLE
Mention course (id?) in emails for temporary confirmation of registration to a course

### ISSUE THREAD

**Issue by renatobellotti** [tanzquotient/tq_website#102]
Mention what course on what day is meant. Perhaps also put a link to the course description.

The same issue exists for cancellation emails.

**Comment by roggnroll** [comment]
Currently it is this:

Hi <removed>,

Thank you for registering for the course Salsa Puertorriqueña 1 in "HS 2017 Q1".
Within the next few days, you will receive an email from us confirming whether you have been granted a place in this course.
As you have enrolled as a single, we will try to find a partner for you. On success, you will receive your partners' contact details together with the enrolment confirmation for the course. You may receive this email only some days before the start of the course.

Best regards,

Your TQ-team
tanzquotient.org
If you have any questions concerning the course, feel free to contact us: tanzen@tq.vseth.ch

**Comment by renatobellotti** [comment]
I think there have been no more issues with that, and to me it seems to be ok. Do you still consider this an issue or can we close it?

**Comment by roggnroll** [comment]
I don’t think it’s an issue - thanks
