### ISSUE TITLE
Remove old website URL from email templates

### ISSUE THREAD

**Issue by roggnroll** [tanzquotient/tq_website#104]
Hallo Tobias
Deine Teilnahme am Kurs Tanzquotient-Unicontanz-Austausch im "Workshops HS 2017" ist nun definitiv. Du nimmst alleine an einem Partnerkurs teil bzw. das System weiss nichts von deinem Partner. Solltest du keine spezielle Abmachung mit dem TQ haben, dann melde dich bitte bei uns!

{Bank details removed}

Im Kurs selbst nehmen wir nur noch in Ausnahmefällen Geld an!

Wir freuen uns auf dich!

Dein TQ
_**tq.ethz.ch**_
Bei fragen wende dich an tanzen@tq.vseth.ch

**Comment by martinzellner** [comment]
I checked. This is already done.
