### ISSUE TITLE
Think of a solution for collecting photos of bills for Quästur

### ISSUE THREAD

**Issue by renatobellotti** [tanzquotient/tq_website#112]
Also put a comment telling what the bill is for.

Info: Date, Reason, Name (who paid), Receiver (who got the money --> make this clear), Amount, optional comment

Google form?

Cloud drive?

Email account?

Website? (App?)

**Comment by gitsimon** [comment]
The only real benefit from having this integrated into the TQ system is that we can link the bill to the user account. There is already a profile extending model holding payment information gor teachers. That can be used also for arbitrary registered users. I would recommend to require a login first always before adding a bill.

**Comment by renatobellotti** [comment]
Not important, treasury now collects bills by email.
