### ISSUE TITLE
Certificate renewal script does not work

### ISSUE THREAD

**Issue by martinzellner** [tanzquotient/tq_website#114]
The problem here is that cron and Docker are not working together so well. The possible options here are:
* try to fix it by running a cron daemon in Docker
* Run the certbot renewal on the host and mount the certs into the container. We need to check if nginx (who terminates SSL) reloads automatically if the certs change.

**Comment by renatobellotti** [comment]
Can be done manually, not so important.

**Comment by renatobellotti** [comment]
Perhaps this is helpful:
https://www.humankode.com/ssl/how-to-set-up-free-ssl-certificates-from-lets-encrypt-using-docker-and-nginx

**Comment by thgoebel** [comment]
Should be fixed now.
Will go away anyway once we're on VSETH's infrastracture :blush:
