### ISSUE TITLE
Think of a solution for sharing incoming emails

### ISSUE THREAD

**Issue by renatobellotti** [tanzquotient/tq_website#128]
Use existing software? Write a new system?

The solution should make it possible to assign emails to a certain person and/or a group of persons.

Perhaps a ticket system?

**Comment by roggnroll** [comment]
Do we really need this?
I would ask VSETH for more email accounts.
We actually have one more, 
anmeldungen@tq.vseth.ch
no one seems to use it though

**Comment by renatobellotti** [comment]
Not really a bug, there is no need for this.
