### ISSUE TITLE
Tanzgruppen

### ISSUE THREAD

**Issue by andraema** [tanzquotient/tq_website#13]
neben Kursen auch Tanzgruppen, die sich selbst organisieren. Anmeldung läuft aber über die Website.

**Comment by roggnroll** [comment]
Okay wie soll das genau aussehen? 
Wodurch unterscheiden die sich durch die regulären Kurse?
- kostenlos
- kein Lehrer
Wo genau fliesst das der TQ ein? Er stellt einfach nur das Informationssystem (Homepage) zur Verfügung? Oder organisiert auch den Raum?
Wie wichtig ist dieses Feature (wie gross ist die Nachfrage?)
