### ISSUE TITLE
People who haven't paid shouldn't be able to subscribe

### ISSUE THREAD

**Issue by renatobellotti** [tanzquotient/tq_website#132]
People who have open bills shouldn't be allowed to subscribe to new courses.

**Possible solutions:**
- Try to detect "multi accounts" by finding name duplicates (mark them for manual inspection).
- Use the SwitchAAI to authenticate students. This won't work for external people, though. (But those are a small minority... Manual handling might be possible with acceptable effort.)

**Comment by martinzellner** [comment]
I like the Switch Authentication Idea. Maybe we can combine this with #147 (SMS Verification)

**Comment by martinzellner** [comment]
This is also related to #110

**Comment by renatobellotti** [comment]
Information about how SwitchAAI works + related terminology: https://www.switch.ch/aai/demo/simple/

**Comment by renatobellotti** [comment]
Related to issue #144.

**Comment by TobiMarg** [comment]
See #144
