### ISSUE TITLE
Create test accounts for different roles

### ISSUE THREAD

**Issue by renatobellotti** [tanzquotient/tq_website#133]
This makes it possible to test if people with certain rights can access what they need. They shouldn't be able to do things that they don't need to do their job.

**Comment by renatobellotti** [comment]
Max Muster is the teacher.

**Comment by roggnroll** [comment]
Please send the IT the credentials in an encrypted chat

**Comment by renatobellotti** [comment]
Add these things to the testing fixture in ```test_config/test_env_dump``` (currently in the blacklist folder)

**Comment by DanielSparber** [comment]
Any board member can just create test users ;)
