### ISSUE TITLE
Something strange with course management

### ISSUE THREAD

**Issue by renatobellotti** [tanzquotient/tq_website#135]
![bildschirmfoto von 2017-11-10 23-13-26](https://user-images.githubusercontent.com/10884299/32680832-dde21ea0-c66c-11e7-866b-b84f53e2a565.png)

Find out what's wrong.

**Comment by renatobellotti** [comment]
This was caused when @roggnroll was logged in and tried to change something for the Social 4+ offering... Do you remember what it was?

**Comment by roggnroll** [comment]
I tried to add and remove people...

**Comment by roggnroll** [comment]
I remember playing around at bit yah, but no malicious attempts I swear ;)

**Comment by renatobellotti** [comment]
Do you mean creating an user account, or adding them to a course?

**Comment by roggnroll** [comment]
only adding them to the course

**Comment by roggnroll** [comment]
Can we close this?

**Comment by renatobellotti** [comment]
I think there was something wrong, but since the error did not occur again, it is ok for the moment.
