### ISSUE TITLE
Show how many Enrolments are from UZH, ETH and how many are non-students

### ISSUE THREAD

**Issue by roggnroll** [tanzquotient/tq_website#136]
In the statistics section, for instance:
https://tanzquotient.org/en/courses/auth/offering/21/
Instead of just showing how many enrollments are men/female confirmed show the whether they are UZH, ETH, PH, non-student.

![d](https://user-images.githubusercontent.com/26879902/32726583-b75e7c9c-c879-11e7-8a63-e3d539ca8094.PNG)

**Comment by renatobellotti** [comment]
It is implemented, but now the statistics page is really slow.
The current implementation queries ALL data from all subscriptions, even though only the student status is needed. Realise this using filters.

**Comment by roggnroll** [comment]
Can I close this? I don’t think it’s slow. Nice graph! Excellent work!

**Comment by renatobellotti** [comment]
Thank you! :) I agree, it seems that there is some sort of caching going on, it's much faster than before.
