### ISSUE TITLE
Restore Buttons For Courses and Events

### ISSUE THREAD

**Issue by roggnroll** [tanzquotient/tq_website#137]
Desired-State:
![bildschirmfoto 2017-11-14 um 08 57 55](https://user-images.githubusercontent.com/26879902/32768890-f8f547c6-c919-11e7-9e10-9df2e6c07d51.png)
Is-State:
![bildschirmfoto 2017-11-14 um 08 59 42](https://user-images.githubusercontent.com/26879902/32768930-264e6126-c91a-11e7-95c6-213c5e9a0014.png)

**Comment by roggnroll** [comment]
Aha, the "Button" is a plugin. This plugin seems to have a different version on the live server and thats why it's not working. When you try to edit the button in the CMS you will see a slightly different editor.

**Comment by roggnroll** [comment]
HTML code what it should generate:
```
<a class="btn btn-action btn-lg cms-plugin cms-plugin-104" role="button" href="/en/courses/">
    Show courses</a>
```
HTML code what it now generates:
`<a href="/en/courses/">Show courses</a>`

**Comment by renatobellotti** [comment]
Thank you very much, Anna and Fabian! :)
