### ISSUE TITLE
Detect USIs better for Payments

### ISSUE THREAD

**Issue by roggnroll** [tanzquotient/tq_website#138]
Detect also the following USI patterns
`USI - 04EC84`
`USI- 04AGF0`
`USI-04A F5D`
`USI 040LFE`

**Comment by roggnroll** [comment]
This should be easily achieved with regular expressions

**Comment by renatobellotti** [comment]
Please also consider the [standard](http://www.cftc.gov/idc/groups/public/@swaps/documents/dfsubmission/usidatastandards100112.pdf).

**Comment by martinzellner** [comment]
Haha :D This "Standard" is just a coincidence. Actually the term "USI" was born as an abbreviation for "Unique Subscription Identifier"

**Comment by renatobellotti** [comment]
Oh, good to know.
@martinzellner So the USIs are generated by our own code?
@roggnroll Where have these USIs occurred? If the USIs are generated and used only by our own system, and there are identifiers that are not recognized, there is probably a bug in the generation and/or matching code.

**Comment by renatobellotti** [comment]
It seems that there have not been any more issues. See also #168 and #167 .
