### ISSUE TITLE
Export everywhere as xlsx, not csv

### ISSUE THREAD

**Issue by roggnroll** [tanzquotient/tq_website#139]
In courses/services.py
`export_subscriptions(course_ids, export_format):`
has an option to export xlsx not csv
`export_summary` and `export_teacher_payment_information` do not have this feature yet

For the user this means that teachers can export the list of students of a course as xlsx, but admins like us cannot export all the teachers of an offering in xlsx, only csv

**Comment by renatobellotti** [comment]
What's the problem with CSV? You can open it in the same program...

**Comment by roggnroll** [comment]
You can yes. Unfortunately Excel is not the brightest of programs and it will just insert the contents of the file as text if you double click it:
![bildschirmfoto 2017-11-16 um 07 02 57](https://user-images.githubusercontent.com/26879902/32876416-0ec9a0fe-ca9d-11e7-81b5-fd9ee8f48996.png)
You have to manually go via "Data", "Insert" 
![bildschirmfoto 2017-11-14 um 21 14 45](https://user-images.githubusercontent.com/26879902/32876461-440dd5dc-ca9d-11e7-81ab-1d43d47117cf.png)
and select comma as delimiter
![bildschirmfoto 2017-11-14 um 21 15 23](https://user-images.githubusercontent.com/26879902/32876472-51e71132-ca9d-11e7-979f-ad948dd12609.png)
No problem for me but other users get stuck and have to ask

**Comment by renatobellotti** [comment]
I think Libreoffice displays it correctly, but if people want to pay for a non-functional piece of software, I will of course add an option to export in Excel format.

**Comment by roggnroll** [comment]
unfortunately this is what people want to do...
(I'm totally on your side - but really most people use excel sadly)

**Comment by roggnroll** [comment]
Apple Numbers and Google Sheets also do it correctly.
I don't get why Excel doesn't get what the separator is in file name that is called CSV - _**COMMA**_ (hint, wink wink, hello) separated file
