### ISSUE TITLE
FAR FUTURE: TQ Android app

### ISSUE THREAD

**Issue by renatobellotti** [tanzquotient/tq_website#141]
Just a thought. Perhaps, there's a bigger team at some point in the future.

**Comment by martinzellner** [comment]
What would the benefit of this be?

**Comment by renatobellotti** [comment]
- Users would not have to log in (except for the first time)
- Fast (and offline) look up of course locations and times
- Possibility for teachers to fast inform students about changes (?)
- Would be a nice reason to pack our business logic into a REST API, which is inherently modular and easy to test
- "Native feel" (whatever that means...)

**Comment by DanielSparber** [comment]
No valid use case, to much overhead

Improve website instead
