### ISSUE TITLE
Implement waiting list

### ISSUE THREAD

**Issue by renatobellotti** [tanzquotient/tq_website#143]
For a course. Probably start by saving the registration date.

**Comment by roggnroll** [comment]
Why do we need this? What's wrong with the current "waiting list"?

**Comment by renatobellotti** [comment]
If I understood Dance Administration correctly, there is currently no waiting list implemented.

**Comment by gitsimon** [comment]
the waiting list is implicit, since we have already a time stamp when the registration was made.

**Comment by renatobellotti** [comment]
Ok, so there's basically nothing to do. Thank you, Simon!

It'd perhaps be nice to have an admin action to list the people on the waiting list of a course (and/or of all recent courses).
