### ISSUE TITLE
Blacklist: State in user profile if there's an unpayed payment

### ISSUE THREAD

**Issue by renatobellotti** [tanzquotient/tq_website#144]

**Comment by britschki** [comment]
Idea:
- add list of user's courses to user profile with an associated payment status: 
   - ok
   - first reminder
   - second reminder
   - teacher intervention
   - blacklisted
- add a global status field to user profile table with the following options:
   - ok
   - first reminder
   - second reminder
   - teacher intervention
   - blacklisted
- global status is worst case status across all open/closed payments
- create blacklist table
- celery task to update user status periodically (daily). 
   - calculate payment status for each course
   - send corresponding e-mails if status has changed (recipients TBD). 
   - recalculate global status
   - add users to blacklist if necessary. 
- when user makes payment, update status accordingly

- also write unit tests

**Comment by renatobellotti** [comment]
A first version of the models is implemented (not committed yet). The blacklist status of the subscription is set to 'OK' if the subscription is payed.
Still to do:
- Write celery task that updates the blacklist status for unpaid subscriptions (e. g. daily)
- Add code to send out emails if the blacklist status has been changed.

**Comment by renatobellotti** [comment]
Update (commit a488ef9b9d5cf410397da5a71fad05fd761cc77c):

The code to update the blacklist is implemented, but not tested yet (not even executed...).
The remaining task is to let Celery call the ```update_entire_blacklist()``` function in ```courses/services.py``` periodically.
