### ISSUE TITLE
Have different types of emails sent from different e-mail adresses

### ISSUE THREAD

**Issue by roggnroll** [tanzquotient/tq_website#146]
For instance (these are just examples the names do not necessarily have to be like this):
payment reminders from 
payment@tq.vseth.ch

No Partner found from
partner@tq.vseth.ch

Enrollment confirmation
enrollment@tq.vseth.ch

These can then be redirected to an arbitrary account (or more than one).
This allows easy filtering.

**Comment by renatobellotti** [comment]
Will be solved by solving #65.
