### ISSUE TITLE
Mark payment file only as processed if all payments were performed successfully

### ISSUE THREAD

**Issue by renatobellotti** [tanzquotient/tq_website#149]
Possible solution: Save all payments in the file inside a transaction
There can two things happen:
- All payments are successfully saved.
- No payments are saved if there occurs a problem with at least one saving operation.
--> The admin has to find out the cause and fix it.

PRO: It is made sure that no payments go missing while processing the ISO 2022 files.
CON: An error in one payment blocks the entire payment system!

I think it is better to have as much consistency and provable certainty of the system state as possible.

**Comment by martinzellner** [comment]
maybe we can throw an exception to sentry and mark the file as `.error`

**Comment by renatobellotti** [comment]
Good idea! I close this issue for now and open a more general one (#154), which we'll discuss in one of our next meetings.
