### ISSUE TITLE
Adapt the backup script(s) on the server so that the backups are only written to disk encrypted

### ISSUE THREAD

**Issue by renatobellotti** [tanzquotient/tq_website#152]
Right now, there is a very short time window during which the database dump is unencrypted.

Possible solution: Pipeline the encryption command instead of calling it later.

The other script does only a backup of the tq_website database, but does not encrypt it at all!

**Comment by martinzellner** [comment]
Why is it a threat if the dump is unencrypted on the production system? Someone with access to the production system can always access the database directly anyways.

**Comment by renatobellotti** [comment]
You're right, but the dumps have to be encrypted before uploading them to the cloud (for privacy reasons, especially for later when Shibboleth integration is implemented...)

**Comment by martinzellner** [comment]
If I remember correctly, they are!

**Comment by renatobellotti** [comment]
You're right, the current backup script does encrypt the dump. The other script is never used, if I haven't overseen anything.
