### ISSUE TITLE
Add Checkbox for course enrolments

### ISSUE THREAD

**Issue by roggnroll** [tanzquotient/tq_website#153]
- "Hiermit bestätige ich dass ich nach Erhalt der Teilnahmebestätigung verpflichtet bin die volle Kursgebür zu zahlen."
- "Hiermit akzeptiere ich die Teilnahmebedingungen des TQs."

**Comment by renatobellotti** [comment]
Add "the registration is binding".

**Comment by renatobellotti** [comment]
This is done by now.
