### ISSUE TITLE
list people who are willing to help

### ISSUE THREAD

**Issue by roggnroll** [tanzquotient/tq_website#157]
Like people who have signed up for the newsletter
Also: NEEDs A FEATURE THAT DELETES DUPLICATE EMAILS - Because this creates errors in the VSETH Alias system - Duplicate Emails come from users having multiple accounts...

**Comment by roggnroll** [comment]
This would be important

**Comment by roggnroll** [comment]
@Fa741 would you like to do this?

**Comment by roggnroll** [comment]
I don’t think it’s a lot of effort. Basically the code already exists for the people that want the newsletter, you only have to copy and slightly adapt it

**Comment by renatobellotti** [comment]
It is already implemented if I see it correctly?



![bildschirmfoto von 2018-03-04 09-41-46](https://user-images.githubusercontent.com/10884299/36943833-7d9d2d8c-1f90-11e8-9853-cbf6c1ab6063.png)

**Comment by roggnroll** [comment]
Hm but how do I get a list of all their emails automatically, like for the newsletter?

**Comment by roggnroll** [comment]
yah i guess it's okay to copy over to excel

**Comment by roggnroll** [comment]
This feature would still be nice. Using excel is extremely tedious. 
ESPECIALLY - I NEED A FEATURE THAT DELETES DUPLICATE EMAILS - Because this creates errors in the VSETH Alias system - Duplicate Emails come from users having multiple accounts...

**Comment by DanielSparber** [comment]
Implemented (and no more duplicates)
