### ISSUE TITLE
Add VSUZH Logo

### ISSUE THREAD

**Issue by roggnroll** [tanzquotient/tq_website#158]
(Logo can be found in google drive)

**Comment by renatobellotti** [comment]
Where? In the footer?

**Comment by roggnroll** [comment]
Yes, next to the VSETH logo

**Comment by renatobellotti** [comment]
I've added the logo, but the contrast isn't very good... Perhaps our propaganda person wants to make a better one?

**Comment by roggnroll** [comment]
I've added a small one
