### ISSUE TITLE
assign same adress to multiple Rooms

### ISSUE THREAD

**Issue by melissazacharias** [tanzquotient/tq_website#159]
At the moment, two rooms cannot have the same adress. Selecting an adress twice results in an error message. This needs to be changed as we now have multiple rooms in the same building.

**Comment by renatobellotti** [comment]
The problem is that the Room model in courses/models.py defines the address as a OneToOneField. This should be changed.

[Related documentation]( https://docs.djangoproject.com/en/2.0/topics/db/examples/one_to_one/)

**Comment by gitsimon** [comment]
Yes you could change this, but think about it: if rooms share addresses (link to the same address instance), you will have possibly undesired side effects when you edit one room's address. As the address model is also used by user profiles, I decided to never share addresses between objects at the time of writting that models.

**Comment by roggnroll** [comment]
can't you add the room number other some other extra information to the address?

**Comment by roggnroll** [comment]
Not considered an issue - include room numbers in issue
