### ISSUE TITLE
new function: mark participants in red 

### ISSUE THREAD

**Issue by ariannam** [tanzquotient/tq_website#164]
option to mark participants in red in "Kurse -> Anmeldungen"

**Comment by renatobellotti** [comment]
Do you mean in the admin interface or in the page itself (i. e., what the users see)? What would be the benefit of this?

**Comment by ariannam** [comment]
Yes, the Admin interface.
Some participants have special requests, like partner enrolls a few days later.
I need to know which I can include in my normal confirmation and matching process and which ones to leave out.

**Comment by renatobellotti** [comment]
The admin interface is generated automatically, we don't have direct influence on what it looks like (at least not with proportional effort). We could write an export tool that gives you a nicely formatted spreadsheet, if you want.
