### ISSUE TITLE
Multiaccounts cause emails to show up in both subscribe-to-newsletter and unsubscribe-to-newsletter lists

### ISSUE THREAD

**Issue by roggnroll** [tanzquotient/tq_website#170]
many people which multi-accounts have in one account checked that they want a newsletter and in another that they don't want it - this causes their email to show up in both the subscribe-to-newsletter and unsubscribe-to-newsletter lists. Depending on which order you submit it to the VSETH system, they will receive the newsletter or not.

**Comment by renatobellotti** [comment]
Solution (manually): Make unused accounts inactive.

**Comment by DanielSparber** [comment]
Resolved, since there are no more duplicate emails in auth_user
