### ISSUE TITLE
Change sending email address form "tanzen@..." to "anmeldungen@..."

### ISSUE THREAD

**Issue by renatobellotti** [tanzquotient/tq_website#175]

**Comment by roggnroll** [comment]
any success here?

**Comment by martinzellner** [comment]
Done. This was actually very, very easy (just edit the .env file)

**Comment by renatobellotti** [comment]
We knew this, but it didn't work the last time. Further testing needed.

**Comment by martinzellner** [comment]
Any reason why this should still be open?
