### ISSUE TITLE
Facilitate sorting of outgoing payments

### ISSUE THREAD

**Issue by annmoser** [tanzquotient/tq_website#187]
Add a new "TYPE" on the TQ Website for online payments. Goal is that I can manually mark payments that I have collected in the payment summary as "archived".

**Comment by renatobellotti** [comment]
Introduce another type "completed"

**Comment by kadirakin85** [comment]
Is it OK with this change ? There is also now Archive as a Type for payments.

**Comment by annmoser** [comment]
I found the "archive" as type for payments, thanks
Unfortunately, there is still one bug (necessary) and something I would like to have (nice to have)

I marked a few debit payments as "archive". Suddenly, everything changed back "irrelevant". I pressed the save button everytime. I tried it again and the same thing happened after about 10 payments. It seems like the type "irrelevant" is a default for debit payments and cannot be overwritten (for the moment).

It would be fantastic, if the option "mark debit payments as ARCHIVE" would be in the drop down menu, so that I just can mark all the payments I want and set them to "archive" in one go.

Of course, the first issue is the important one. The second is just nice to have...
Thanks!

**Comment by kadirakin85** [comment]
![tq_archieve](https://user-images.githubusercontent.com/37308918/39527298-5ed5915e-4e21-11e8-97f1-da8d8d4c8980.png)

I couldnt regenerate the bug that you mentioned. Somehow for me it works fine as shown in attached figure. Renato, do you have an idea ? 

I will check if I can make  "archive in one go" option, I will look at that on Saturday.

**Comment by renatobellotti** [comment]
Which payments would you like to change to ARCHIVE type? (please no names, only payment IDs)

**Comment by renatobellotti** [comment]
@kadirakin85, @annmoser  after thinking again about it, it would make more sense to me to add ARCHIVE as an additional STATE, not TYPE. What do you think?

@annmoser I understand that you need to make the changes yourself. That should definitely be possible because you have full admin permissions. If I understood correctly, the TYPE attribute is reset after some time? (Please do not try this now because this would mean to lose data in case we decide to make "archive" a STATE)

**Comment by renatobellotti** [comment]
It came to my mind what is wrong: We forgot to make and perform the database migration, so the database does not "know" about the new TYPE.

**Comment by renatobellotti** [comment]
It should be working for good now. The button is still under construction. :)

**Comment by kadirakin85** [comment]
Now we have a new function called "Archive selected Payments" to allow one go action. Archive is now a state, but not a type.

**Comment by kadirakin85** [comment]
And the new function will be working after Renato updates the server.

**Comment by renatobellotti** [comment]
The changes should now be online.

**Comment by annmoser** [comment]
Thanks for all the work! Now it also works for me as hoped, also as non-administrator. I'd consider this chapter closed :)
