### ISSUE TITLE
Users cannot alter their profile information

### ISSUE THREAD

**Issue by renatobellotti** [tanzquotient/tq_website#198]
A user reported:

> I have tried to update my profile and it will not save my new content and just reverts back to the old which is not correct anyway.
More precisely, it was about changing his address information.

**Comment by TobiMarg** [comment]
I already tried to pinpoint this error but I couldn't reproduce it and the user management source code is very bloated, but without any obvious bug. So I'll just try to simplify the code a bit and hopefully make it more reliable.
