### ISSUE TITLE
Make description of free places in courses less confusing

### ISSUE THREAD

**Issue by renatobellotti** [tanzquotient/tq_website#204]
The current description is quite confusing:
![free_places](https://user-images.githubusercontent.com/10884299/47736455-01887200-dc6f-11e8-8a69-a4ab92615a9e.jpg)
![free_places2](https://user-images.githubusercontent.com/10884299/47736465-051bf900-dc6f-11e8-8ab8-9316a6ec9d86.jpg)
Does that mean that man/women are free to enrol?

**Comment by TobiMarg** [comment]
While changing/fixing that we should also think about the all other possible cases like when there is a "waiting list".
