### ISSUE TITLE
Shift birth date from general profile to Salary Payment Info

### ISSUE THREAD

**Issue by annmoser** [tanzquotient/tq_website#210]
Every now and then teachers enter their Salary Payment Info, but forget to fill in the birth date. I think this is because the birth date is in the normal profile. Can we move the birth date to the Salary Payment Info?

**Comment by renatobellotti** [comment]
The birthdate is also needed to match partners for single subscriptions. Therefore we need it also for students. Perhaps we can introduce a "check teacher profile" button or add an admin action to send an email to teachers with an incomplete profile, would that be ok?

**Comment by renatobellotti** [comment]
i think the matching is mostly done by hand, but it never hurts to have the info. 1st yesr students are probably a bit too shy to dance with PhD students ;)
