### ISSUE TITLE
IBAN numbers mixed up

### ISSUE THREAD

**Issue by annmoser** [tanzquotient/tq_website#211]
The IBAN numbers of teachers' profiles get mixed up all the time. This is not because we change them, but because something happens in the system.

What is also strange is the following: AHV numbers appear for me as a text, but the IBAN number appears as a drop-down menu, where I can select among all bank account numbers in our database. Maybe when you can change the bank account details to the same format as the AHV number, the error disappears

**Comment by renatobellotti** [comment]
That sounds very weird. I'll take a look at this after my last exam on the 11th of February.

**Comment by renatobellotti** [comment]
Thanks for letting me know. I don't understand why bank accounts are stored as references, but I'll check the entire source code to make sure nothing is messed up when I change this.
