### ISSUE TITLE
Teacher profiles

### ISSUE THREAD

**Issue by annmoser** [tanzquotient/tq_website#218]
Teachers should have the possibility to enter a short description in their profiles. This should then be published on the course detail pages similarly to the board members. If you click on the name, the description should appear.

As an easy, but not long term fix it might be possible to implement it the same way it works for board members. Then one of us has to copy the text of each teacher into their profiles, as they do not have access to that area of the website.

**Comment by DanielSparber** [comment]
Teachers can enter their description
