### ISSUE TITLE
Continuous delivery

### ISSUE THREAD

**Issue by DanielSparber** [tanzquotient/tq_website#221]
- Get current master from Github
- ./scripts/migrate.sh
- ./scripts/makemessages
- Import translations from POEditor
- ./scripts/compilemessages
- docker-compose stop 
- docker-compose -f docker-compose-production.yml start

**Comment by thgoebel** [comment]
Obsolete once migrated to VSETH SIP.
We should nevertheless document these steps as part of #257 just for the reference.
