### ISSUE TITLE
Update to State-of-the-art versions

### ISSUE THREAD

**Issue by martinzellner** [tanzquotient/tq_website#243]
When the project was created Django 1.x was the latest and greatest. In the meantime Django 3.0 is available and old versions have a lot of security flaws.

As the second important dependency, django-cms is not yet compatible I suggest upgrading to Django 2.2.

@DanielSparber This might be my Christmas coding project. Let me know if you consider this a good idea.

**Comment by DanielSparber** [comment]
I agree! Maybe not around christmas :D
