### ISSUE TITLE
Migrate from MySQL to Postgres

### ISSUE THREAD

**Issue by thgoebel** [tanzquotient/tq_website#247]
Helpful links:

* https://www.calazan.com/migrating-django-app-from-mysql-to-postgresql/
* https://gist.github.com/sirodoht/f598d14e9644e2d3909629a41e3522ad
* https://stackoverflow.com/questions/3034910/whats-the-best-way-to-migrate-a-django-db-from-sqlite-to-mysql

Work started on branch [migrate-to-postgres](https://github.com/tanzquotient/tq_website/commits/migrate-to-postgres).

**Comment by DanielSparber** [comment]
Done
