### ISSUE TITLE
Course cancellation email to teachers

### ISSUE THREAD

**Issue by barblu** [tanzquotient/tq_website#253]
When we cancel a course, registered students get a notification that the course has been cancelled. Could we send the same email to the teachers as well? Otherwise I (Luisa) have to send an email to the teachers separately.

**Comment by DanielSparber** [comment]
Should be possible, I'll look into it

**Comment by DanielSparber** [comment]
How do you cancel a course?
Reject all participants? Or is there another function to do this?
