### ISSUE TITLE
About - Köpfe der Vorstandsmitglieder

### ISSUE THREAD

**Issue by annmoser** [tanzquotient/tq_website#264]
Die Reihenfolge sollte wie folgt lauten:
Präsident
Vizepräsident
Finanzen
Tanzadministration
Events
Komm&Marketing
IT
Aktuariat

Bei Doppeltbelegung soll der Nachname gelten

Aktuar sollte in Aktuariat umgewandelt werden, um es ebenfalls geschlechterlos zu haben.

Ebenfalls ist mir aufgefallen, dass die Titel auf der englischen Seite deutsch sind. Wäre cool, wenn das auch angepasst werden kann.

**Comment by DanielSparber** [comment]
Issues bitte auf Gitlab eintragen:

https://gitlab.ethz.ch/vseth/0500-kom/0519-tq/sip-tq-apps/website/-/issues
