### ISSUE TITLE
Default Collation MySQL UTF-8

### ISSUE THREAD

**Issue by gitsimon** [tanzquotient/tq_website#34]
Ensure database within mysql docker container is created with utf8 default collation (latin1 is default)

> drop database tq_website;
> CREATE database tq_website DEFAULT CHARACTER SET utf8;
> (Check problems with utf8, maybe use utf8mb4)

**Comment by martinzellner** [comment]
This is fixed in branch mysql-encoding. We need to recreate the docker mysql container and restore the database after merging this to master.

**Comment by martinzellner** [comment]
This is hard to fix on the live database. If someone feels like diving into MySQL encodings, go ahead, but be careful!

**Comment by DanielSparber** [comment]
We are not using MySQL anymore
