### ISSUE TITLE
Mark old courses all as paid

### ISSUE THREAD

**Issue by martinzellner** [tanzquotient/tq_website#44]
The "owes" field does not make a lot of sense since for old subscriptions the payed field was not used

**Comment by martinzellner** [comment]
Subscriptions in state "completed (to pay)" are now payed for the year 2015. Ask Kim on how to proceed with the year 2016.

**Comment by renatobellotti** [comment]
Has this been done by now?

**Comment by martinzellner** [comment]
This should be clarified with finance.

**Comment by roggnroll** [comment]
what's the current status here?

**Comment by roggnroll** [comment]
@martinzellner What's the status?

**Comment by renatobellotti** [comment]
I'd suggest to discuss this with Daria at our next meeting.
