### ISSUE TITLE
Course money received by TQ

### ISSUE THREAD

**Issue by martinzellner** [tanzquotient/tq_website#45]
To support finance the following properties would be nice to have on course level:
- [ ] list teachers view
-  [ ] overall amount of course income
-  [ ] overall wages per teacher
-  [ ] overall hours per teacher
-  [ ] list due cash payments with possibility to mark them as received 
-  [ ] booked in SAP

**Comment by martinzellner** [comment]
Partly implemented

**Comment by martinzellner** [comment]
Updated Feature List

**Comment by renatobellotti** [comment]
Similar to #120.

**Comment by martinzellner** [comment]
This is indeed a duplicate of #120
