### ISSUE TITLE
Reimbursment

### ISSUE THREAD

**Issue by gitsimon** [tanzquotient/tq_website#66]
We need a (manual) process to pay back course payment to subscribers, in the case of:

- [ ] Cancellation of complete course
- [ ] Cancellation through the partner and no new partner could be found
- [ ] Cancellation of single lessons (e.g. because of room not available)?
- [ ] Cancellation through the subscriber itself (with good reasons)?

**Comment by renatobellotti** [comment]
Agreed to be not desired.
