### ISSUE TITLE
Flexible Format for Legis from other Universities

### ISSUE THREAD

**Issue by gitsimon** [tanzquotient/tq_website#68]
We accept all students from Zurich (Switzerland?)

**Comment by renatobellotti** [comment]
I'm not sure if we even need to change something... According to http://registration.fernuni.ch/registration/ and this ancient forum post https://forum.vis.ethz.ch/showthread.php?11359-Immatrikulationsnummer-aufgeschl%FCsselt the Matrikelnummer has the same format for all Swiss universities.
Do we have a concrete example of a legi number that could not be entered?

**Comment by martinzellner** [comment]
Foreign Legis (e.g. Germany) might not have the same format. Does it hurt to accept arbitrary numbers?

**Comment by renatobellotti** [comment]
This is not needed anymore if authentication via Shibboleth is implemented, see #110 .
