### ISSUE TITLE
Make list of E-mails in subscriptions copyable

### ISSUE THREAD

**Issue by renatobellotti** [tanzquotient/tq_website#71]
So you can insert it into your mail program.

**Comment by roggnroll** [comment]
![bildschirmfoto 2017-10-19 um 12 33 37](https://user-images.githubusercontent.com/26879902/31767012-e1738c3e-b4c9-11e7-9ef7-74aec6511115.png)

**Comment by roggnroll** [comment]
At the moment the generated list does not separate the addresses through commas

**Comment by renatobellotti** [comment]
They are separated by comma if you copy & paste the adresses into Thunderbird. It doesn't work for the outlook web interface

**Comment by renatobellotti** [comment]
It's now working. Please test on Windows and iOS devices, I have tested on Linux (Fedora 26 with Thunderbird) and on the ETH Webmail, so we have at least one solution that works for all
