### ISSUE TITLE
Add spell checker

### ISSUE THREAD

**Issue by renatobellotti** [tanzquotient/tq_website#73]
For writing email templates etc.

**Comment by roggnroll** [comment]
This is less important as people should just have this on their OS (like Safari on Mac) or an appropriate plugin (for instance with Firefox)

**Comment by martinzellner** [comment]
For English, [Grammarly](http://grammarly.com/) is quite nice.

**Comment by renatobellotti** [comment]
Actually the Django CMS editor already has a spell checker built-in which is disabled by default.
I've enabled it.
The 'problem' is now that you have to install a plugin to this editor in order to be able to select the language of the text. I haven't succeeded at that.

**Comment by roggnroll** [comment]
Works for me also for German! The language seems to be auto-detected. I consider this issue closed! Nice job!

**Comment by DanielSparber** [comment]
Job of browser, not TQ system
