### ISSUE TITLE
Update all Python requirements to recent versions

### ISSUE THREAD

**Issue by renatobellotti** [tanzquotient/tq_website#80]
It's also a matter of security (crypto libraries...).
Please test if everything is still working after the updates for each group.
**Check especially the critical features like email and payment processing!**

I suggest to split this quite big task into better manageable groups:

- [ ] **Crypto related:**
- ecdsa
- paramiko
- cryptography
- base36

- [x] Celery:
- celery
- django-celery-email
- django-celery-beat
- django-celery-results

- [x] Django 1:
- Django
- django-absolute
- django-analytical
- django-appconf
- django-classy-tags

- [x] Django 2:
- django-filer
- django-filter
- django-formtools
- django-guardian
- django-parler

- [ ] Django 3:
- django-parler-rest
- django-mptt
- django-polymorphic
- django-post-office
- django-reversion

- [ ] Django 4:
- django-sekizai
- django-bootstrap3
- django-daterange-filter
- django-allauth
- django-debug-toolbar

- [ ] Django 5:
- django-countries
- django-ical
- djangorestframework
- django-sslify

- [ ] Django CMS 1:
- django-cms
- djangocms-admin-style
- cmsplugin-filer

- [ ] Django CMS 2:
- djangocms-googlemap
- djangocms-inherit
- djangocms-link
- djangocms-text-ckeditor

- [ ] Memcached, Redis and Raven:
- python-memcached
- raven
- redis

- [ ]  Image generation:
- Pillow
- unicodecsv
- PyPDF2

- [ ] Everything else:
- easy-thumbnails
- gunicorn
- openpyxl
- mysqlclient
- html5lib [why this strange version number?]

**Comment by martinzellner** [comment]
Splitting this might be tricky as a lot of packages have interdependencies

**Comment by renatobellotti** [comment]
Then it's also a good opportunity to note down the dependencies of each package in the wiki. ;)
I still think it's a good idea to split the task in small pieces, this lowers the "motivation barrier" very much.
If someone realizes that it really won't work, we can still reorganise the groups or even drop them and do everything in one big part.

**Comment by roggnroll** [comment]
ok, can you assign a specific section for me? 
Have you set up a branch yet?

**Comment by renatobellotti** [comment]
I think a good point to start at might be the Django sections. I don't know if it's possible to assign subissues... Just pick the one you like most ;) (pro tip: Django 1 SEEMS to be easy...)
Please don't forget to add the documentation to the wiki as well.
