### ISSUE TITLE
Add a wiki page for the Python dependencies

### ISSUE THREAD

**Issue by renatobellotti** [tanzquotient/tq_website#81]
It's always a good idea to know the purpose of each package and all its dependencies.
This simplifies testing and debugging significantly after an update of the packages.

Please note if a certain version is required (+ the reason why).

**Comment by thgoebel** [comment]
Looks like it's there:
https://tq-website.readthedocs.io/en/latest/infrastructure/used_python_packages.html

Somewhat out of date though. Will be updated in #257.
