### ISSUE TITLE
Allow English and German Titles for Events

### ISSUE THREAD

**Issue by roggnroll** [tanzquotient/tq_website#83]
For events it is currently only possible to have separate German and English Descriptions but not separate Event titles in English and German

**Comment by roggnroll** [comment]
@renatobellotti @gitsimon What would be the best way to solve this database wise?
Create an english name column in the `event_event` table or create a new table where the German and English title are stored alike, similar to the event description in table `events_event_translation`?
(The last approach is certainly better if we ever plan on adding more languages)

**Comment by renatobellotti** [comment]
I think the main issue here is the migration of existing events, regardless of the structure we choose. I'd prefer the approach with a separate table because it'd make it easier to add support for other languages in the future.
I don't know much about Django CMS, but I assume the back end structure will be hidden for users? If not, we should pick the solution that changes as little as possible to the GUI compared to now.

**Comment by roggnroll** [comment]
Migration shouldn't be a problem at the moment as we have very few new events planned.
I don't quite know what you mean with back end structure, but no the users cannot see the structure of the database.
Changes to the GUI should be minimal.

**Comment by roggnroll** [comment]
We could also leave the old name column intact for backward-compatibility

**Comment by gitsimon** [comment]
Django comes with a very advanced translation system for static strings, but not for database fields. Luckily there is an amazing plugin that we are already using called [**django-parler**](https://django-parler.readthedocs.io/en/latest/)

If you have a look at the `models.py` in the event app, you find in the `Event` class
```python
translations = TranslatedFields(
        description=HTMLField(verbose_name='[TR] Description', blank=True, null=True)
    )
```
As you can read in the django-parler documentation, the fields listed inside are automatically represented in separate table (to support arbitrary more languages without changing all database table schemas).

**Note**: you are never manipulating the database directly! This is handled by Django's [automatically created migrations](https://docs.djangoproject.com/en/1.10/topics/migrations/) quiet well.

The case of moving an untranslated one to a translated one, is a little involved: you either

- add translated field (different name should not be necessary) in  migration `a`
- copy current content to german (or english) translation manually
- add another migration `b`, that removes the old untranslated field

Luckily, this problem appeared before, and you could also perform this steps in _a single migration_ without any manual copying of fields! Have a look at [this migration](https://github.com/gitsimon/tq_website/blob/3cdf5cd87b6428a235f0b237c6556f67bca7b472/events/migrations/0007_auto_20160902_1135.py).

This seems complicated, but most of the migration is auto-generated by Django. So the approach is as follows:

- Add translated field (keep old field untouched)
- Let Django create default migration `python3 manage.py makemigrations` (inside docker container or use script)
- add the method `migrate_untranslated`, adapt it and run it at the correct place, so after creating the translated field and before deleting the old field, with `migrations.RunPython(...)`.
