### ISSUE TITLE
Save Event Description when User Clicks on Separate Language Section

### ISSUE THREAD

**Issue by roggnroll** [tanzquotient/tq_website#84]
If you write for instance the English description for an event and click on the German section, the English text will be deleted. You have to save first and then click on the other language.

**Comment by renatobellotti** [comment]
I'm not sure if this can be easily implemented in our website. I think it should be included in DjangoCMS because it's something that should be done in generated (by DjangoCMS) Javascript code. But since I'm not a web developer, I'd be glad to hear some other opinions.
