### ISSUE TITLE
Translation for Course Plugin

### ISSUE THREAD

**Issue by roggnroll** [tanzquotient/tq_website#87]
Add translation for course plugin - just like issue #85 for events

**Comment by roggnroll** [comment]
Run 
`django-admin makemessages -a`
to create the .po files. Works only with gettext
On Mac run 
`brew install gettext`
and then 
`brew link gettext --force`
to make it work ;)
then after you've updated the German text in the .po file you can run
`django-admin compilemessages `
to compile the language files.
Check in the language files as well, we don't compile a second time on the live server

**Comment by Fa741** [comment]
Binary files (.mo) generated with following command:
`docker-compose run --rm django python3 manage.py compilemessages`
