### ISSUE TITLE
Translate Signup Section

### ISSUE THREAD

**Issue by roggnroll** [tanzquotient/tq_website#88]
Similar to issue #87 and #85

**Comment by roggnroll** [comment]
Run 
`django-admin makemessages -a`
to create the .po files. Works only with _gettext_ installed
On Mac run 
`brew install gettext`
and then 
`brew link gettext --force`
to make it work ;)
then after you've updated the German text in the .po file you can run
`django-admin compilemessages `
to compile the language files.
Check in the language files as well, we don't compile a second time on the live server

**Comment by renatobellotti** [comment]
Priority: Translate the sign up and login pages: They're the first thing a user sees.

**Comment by renatobellotti** [comment]
The login page is now fully translated, but not the signup page. (some "default texts" are still in German)

**Comment by thgoebel** [comment]
Login is fully translated, but signup is not (german is ok, english is missing some):

![tq-translation](https://user-images.githubusercontent.com/33295590/77820351-e6c76080-70e1-11ea-91e8-6ff2fd13c0e7.png)
