### ISSUE TITLE
Add hall of fame/timeline for past heads of committee 

### ISSUE THREAD

**Issue by roggnroll** [tanzquotient/tq_website#90]
This looks nice:
https://sbstjn.com/timesheet.js/

**Comment by renatobellotti** [comment]
I like it! :)

**Comment by roggnroll** [comment]
Actually something like a gantt chart would be better:
http://jsgantt.com
(Instead of Tasks we would have the positions, and the resources would be the people that held the post)
Hmmmm...

**Comment by roggnroll** [comment]
Superb! It would be perfect if the user was able in the end to click on the bars and then a little profile would open up to show the "achievements" of the person

**Comment by gitsimon** [comment]
Note that we already include `plotly-latest.min.js`, it is used for the graphs in the course overview. There you can also see how to get the data into the javascript code via a Django template...feels so hacky but is cool!
(Another way would be to get the data needed for the plotly graph by a separate request to a REST endpoint (also included as a plugin already). This is a little more advanced.)

**Comment by renatobellotti** [comment]
Where is it loaded? I see where it's used, but I'm not yet comfortable enough with templates to find where the Javascript library is embedded. It's included via CDN, right?
