### ISSUE TITLE
Add a password strength meter

### ISSUE THREAD

**Issue by roggnroll** [tanzquotient/tq_website#91]
http://www.passwordmeter.com

**Comment by renatobellotti** [comment]
Do we want a Javascript based solution or handle it server side? Or both?

**Comment by roggnroll** [comment]
Just Javascript is fine. This is just a "recommendation" for the user. If he wants to choose a weak password, it's up to the user.

**Comment by DanielSparber** [comment]
Mit Switchaai hinfällig
