### ISSUE TITLE
Add notification system to find replacement teacher if teacher is absent

### ISSUE THREAD

**Issue by renatobellotti** [tanzquotient/tq_website#92]
A possible idea is:
- The teacher notices that he/she cannot give a lesson and activates the notification system on the website.
- People who already finished the course receive an email.
- One of them takes over. If nobody wants to do it before, say, one day before the lesson, the lesson is cancelled and the participants are notified automatically.

**Advantage:**
Once the functionality is implemented and working, no additional administrative effort is needed because everything is automated or handled by the teachers.

**Comment by gitsimon** [comment]
This functionality would be quit easy once we have a good email sending app inside Django. We can send mass mails already, but we should introduce a nice interface for choosing the receivers from automatically created groups, such as all participants from a course, all woman, all teachers, etc.
