### ISSUE TITLE
merge Amea's user profiles

### ISSUE THREAD

**Issue by roggnroll** [tanzquotient/tq_website#98]
Search for amea. It will result in 4 profiles. The first 3 should be merge. The last one (the guy) is another person who used her email address - what should we do with him?

**Comment by roggnroll** [comment]
![bildschirmfoto 2017-09-23 um 10 25 53](https://user-images.githubusercontent.com/26879902/30776549-a068d40e-a0a8-11e7-9e39-858df4e2796f.png)

**Comment by martinzellner** [comment]
This is a quite common issue. Most people have several accounts.
